### ISSUE TITLE
question about definition of p_amp and s_amp in  "MakeExcitationPlanewave"

### ISSUE THREAD

**Issue by alex-qiang** [weiliangjinca/grcwa#4]
* grcwa version: newest version
* Python version: 3.6
* Operating System: Linux 4.4.0

### Description

When I look at  source codes in function "MakeExcitationPlanewave" I get confused. It seems like p_amp acts as electric vector which polarizes perpendicular to the incident plane, and s_amp acts as electric vector which polarizes parallel to the incident plane. I would appreciate it if you could tell me what the context of your definition of p_amp and s_amp is.

![makeExecitationPlanewave](https://user-images.githubusercontent.com/56872494/189483605-b9b10e87-e113-4e0a-90cf-652e2092ce88.png)

**Comment by weiliangjinca** [comment]
`p_amp` and `s_amp` describe magnetic field. So the direction is flipped.

How the coefficient `ai` and `bi` translate to each component of electric and magnetic field can be found here: https://github.com/weiliangjinca/grcwa/blob/5d85c824e3f2243624c23641800f551ee935fac0/grcwa/rcwa.py#L298-L313

**Comment by WangLicheng-HIT** [comment]
> `p_amp` and `s_amp` describe magnetic field. So the direction is flipped.
> 
> How the coefficient `ai` and `bi` translate to each component of electric and magnetic field can be found here:
> 
> https://github.com/weiliangjinca/grcwa/blob/5d85c824e3f2243624c23641800f551ee935fac0/grcwa/rcwa.py#L298-L313

How to understand "`p_amp` and `s_amp` describe magnetic field. So the direction is flipped." ? No matter electric or magnetic field, the definitions of s polarization and p polarization are the same. 
According to the follow figure:
![image](https://user-images.githubusercontent.com/15194193/193304160-bb27f938-c640-419e-a373-4fd668acf58b.png)
I think the TM polarization corresponds to p polarization and TE polarization corresponds to s  polarization，so according to the geometry relation in the figure, the x component of p polarization (i.e TM polarization) is :
`p_samp*cos(theta)*cos(phi)*exp(j*p_phase)`
the x component of s polarization (i.e TE polarization) is :
`-s_amp*sin(phi)*exp(j*s_phase)`
then the total x component is:
`p_amp*cos(theta)*cos(phi)*exp(j*p_phase)-s_amp*sin(phi)*exp(j*s_phase)`
which is inconsistent with your code's expression:
`-s_amp*cos(theta)*cos(phi)*exp(j*s_phase)-p_amp*sin(phi)*exp(j*p_phase)`

Similar inconsistent also appear in the expression of y component in your code, through the figure, I deduce: 
`s_amp*cos(phi)*exp(j*s_phase)+p_amp*cos(theta)*sin(phi)*exp(j*p_phase)`
but your code is:
`-s_amp*cos(theta)*sin(phi)*exp(j*s_phase)+p_amp*cos(phi)*exp(j*p_phase)`

 The above content really confuses me, hope for your explanation, thanks in advance!

**Comment by weiliangjinca** [comment]
Let's clarify things in the simplest scenarios: theta=phi=0. The plane of incidence is xz. Now the electric field of `s` polarization is along y-direction, but the magnetic field of `s` polarization will be along x-direction (recall that for planewave propagating in uniform medium, **H** is perpendicular to both **k** and **E**). Similarly, the magnetic field of `p` polarization will be along y-direction. So that explains the flipping of s and p between your expression and the one in this repo.
