### ISSUE TITLE
How can we correspond Ex and Ey to Es and Ep?

### ISSUE THREAD

**Issue by yzj1348485638** [weiliangjinca/grcwa#5]
* grcwa version:0.1.2
* Python version:3.10
* Operating System:

### Description

I simulate a nanofin with the shape of cuboid(length=dx, width=dy and height=dz). When dx equals dy , the abs of Es and Ep is the same, but the angle of Es and Ep with a difference of pi. However Ex equals to Ey , when simulating the same structure in FDTD. So I wonder how can we correspond Ex and Ey to Es and Ep.

**Comment by weiliangjinca** [comment]
It should be simple to map once you have your angle of incidence?
