### ISSUE TITLE
Anisotropic material and epsilon tensor

### ISSUE THREAD

**Issue by xinthe1989** [weiliangjinca/grcwa#7]
Hi,

I would like to deal with anisotropic material whose epsilon should be a tensor. How can I do in this package?

Thanks!

**Comment by weiliangjin2021** [comment]
It's not implemented yet in this package. But the implementation should be straightforward, although it will take some efforts. E.g. the equation for the eigenvalue problem will be different (the matrix size is doubled).

**Comment by xinthe1989** [comment]
> It's not implemented yet in this package. But the implementation should be straightforward, although it will take some efforts. E.g. the equation for the eigenvalue problem will be different (the matrix size is doubled).

Thanks! S4 may be can do this.
